//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialCRM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinancialCRMEntities : DbContext
    {
        public FinancialCRMEntities()
            : base("name=FinancialCRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Banks> Tbl_Banks { get; set; }
        public virtual DbSet<Tbl_Bill> Tbl_Bill { get; set; }
        public virtual DbSet<Tbl_Category> Tbl_Category { get; set; }
        public virtual DbSet<Tbl_Process> Tbl_Process { get; set; }
        public virtual DbSet<Tbl_Spending> Tbl_Spending { get; set; }
        public virtual DbSet<Tbl_Users> Tbl_Users { get; set; }
    }
}
